spring.application.name=edutrack-backend
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=edutrack
server.port=8080

# Allow cross-origin from React dev server
spring.web.cors.allowed-origins=http://localhost:5173
